# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

name: FPGA interchange CI tests

on: [push, pull_request]

jobs:
  Check-Repository:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: SymbiFlow/actions/checks@main

  Run-Tests:
    runs-on: [self-hosted, Linux, X64]
    container: "ubuntu:20.04"
    strategy:
      matrix:
        device: ["xc7a35t", "xc7a100t", "xc7a200t", "xc7z010", "xczu7ev", "LIFCL-40"]
    env:
      LANG: "en_US.UTF-8"
      DEBIAN_FRONTEND: "noninteractive"
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install
      run: |
        apt-get -qqy update
        apt-get -qqy install build-essential git make \
          cmake python3 wget unzip curl openjdk-11-jdk-headless

    - name: Create environment
      run: make env

    - name: Build CMake
      run: make build

    - name: Run tests
      run: |
        source env/conda/bin/activate fpga-interchange
        cd build
        make all-${{ matrix.device }}-tests -j`nproc`
        make all-${{ matrix.device }}-validation-tests -j`nproc`
        make all-${{ matrix.device }}-simulation-tests -j`nproc`

    - uses: actions/upload-artifact@v2
      with:
        name: fpga-interchange-tests-performance-graphs
        path: |
          **/plot_*.svg
