# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

name: FPGA interchange CI tests

on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: ["xc7a35t", "xc7a100t", "xc7z010", "LIFCL-40"]
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2

    - uses: SymbiFlow/actions/checks@main

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install git make cmake
        git submodule status > .submodules_status

    - name: Cache environment
      id: cache-env
      uses: actions/cache@v2
      with:
        path: env
        key: env-${{ hashFiles('**/environment.yml', '**/requirements.txt', '**/.submodules_status') }}

    - name: Create environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      run: make env

    - name: Build CMake
      run: |
        make update
        make build

    - name: Run tests
      run: |
        source env/conda/bin/activate fpga-interchange
        cd build
        make all-${{ matrix.device }}-tests -j`nproc`
        make all-${{ matrix.device }}-validation-tests -j`nproc`
        make all-${{ matrix.device }}-simulation-tests -j`nproc`
